- deal-service/src/main/java/com/wesell/dealservice/domain/entity/Category.java
- deal-service/src/main/java/com/wesell/dealservice/domain/entity/Product.java
- deal-service/src/main/resources/application.yml
**### 1. Validation에서 제공하는 @Notnull 대신 @Column(nullable=false)을 사용했습니다.**
데이터 베이스 스키마와 일관성을 유지하기 위해 JPA를 사용했습니다. 런타임 검증을 위해 yml파일에 hibernate.check_nullability: true 를 추가했습니다.
+product리스트 오류는 product 필드값 생성시 사라질 오류이니 신경쓰지 않으셔도 됩니다!
>  Category entity 생성

- admin-service/src/main/java/com/wesell/adminservice/config/ModelMapperConfig.java
- admin-service/src/main/java/com/wesell/adminservice/controller/AdminController.java
- admin-service/src/main/java/com/wesell/adminservice/domain/dto/RequestAdminDto.java
- admin-service/src/main/java/com/wesell/adminservice/domain/dto/ResponseAdminDto.java
- admin-service/src/main/java/com/wesell/adminservice/domain/entity/SiteConfig.java
- admin-service/src/main/java/com/wesell/adminservice/domain/repository/AdminRepository.java
- admin-service/src/main/java/com/wesell/adminservice/service/AdminService.java
- admin-service/src/main/resources/templates/index.html
ModelMapper
- DTO와 엔티티 간의 변환에 사용되는 라이브러리
saveSiteConfig
- 받은 값을 json으로 변환시켜서 db에 저장시킨다
convertDtoToJson
- Dto값을 Json으로 변환시키는 역할
테스트용 index.html과 js, css 생성
> feat: 사이트 설정 등록 기능구현

- user-service/build.gradle
- user-service/src/main/java/com/wesell/userservice/domain/entity/User.java
- user-service/src/main/java/com/wesell/userservice/domain/repository/UserRepository.java
- user-service/src/main/resources/application.yml
- user-service/src/test/java/com/wesell/userservice/domain/repository/UserRepositoryTest.java
* 회원 레퍼지토리 수정
- 앞에서 피드백받은 민감정보 처리 완료
- 테스트 시 데이터가 데이터베이스에 들어가지 않는 현상 발생. @Rollback(false)로 각 테스트 메서드 마다 롤백되지 않게 추가. 이후 db반영 원활
- 테스트를 위해 작성해놓은 findByOneId 메서드의 null값 예외처리는 서비스 계층에서 구현해줄 예정이므로 제외.
- 이외에도 수정이나 추가할 사항 있으면 댓글로 작성 바랍니다.
> fix: 회원 레퍼지토리 수정

- deal-service/src/main/java/com/wesell/dealservice/controller/DealController.java
- deal-service/src/main/java/com/wesell/dealservice/domain/SaleStatus.java
- deal-service/src/main/java/com/wesell/dealservice/domain/dto/request/RequestCreateDealPostDto.java
- deal-service/src/main/java/com/wesell/dealservice/domain/entity/Category.java
- deal-service/src/main/java/com/wesell/dealservice/domain/entity/DealPost.java
- deal-service/src/main/java/com/wesell/dealservice/domain/entity/Product.java
- deal-service/src/main/java/com/wesell/dealservice/domain/repository/DealRepository.java
- deal-service/src/main/java/com/wesell/dealservice/service/DealService.java
- deal-service/src/main/java/com/wesell/dealservice/service/DealServiceImpl.java
- deal-service/src/main/resources/application.yml
1. 필드 값을 보니 거래글이 맞는 것 같아 deal post로 엔티티 명칭 변경했습니다. 이에 맞춰 entity table 명칭도 post 로 변경했고 erd cloud에도 db table name 수정했습니다.
2.  category entity 에 List<product>는 생각해보니 dto에 있어야할 필드값 같아서 삭제했습니다! 
3. 디스코드의 자료방 글 참고해서 swagger 설정 파일 수정했습니다.
base branch 설정 잘못해서 다시 올려요 ㅎㅎ,,죄송합니당
> feat: 거래글 등록 기능 구현

- user-service/src/main/java/com/wesell/userservice/controller/UserController.java
- user-service/src/main/java/com/wesell/userservice/domain/entity/User.java
- user-service/src/main/java/com/wesell/userservice/domain/repository/UserRepository.java
- user-service/src/main/java/com/wesell/userservice/dto/RequestSignupDTO.java
- user-service/src/main/java/com/wesell/userservice/dto/responseDto.java
- user-service/src/main/java/com/wesell/userservice/service/UserService.java
회원가입기능구현
메소드설명
controller : signup -(회원가입)
service : save -(저장), convertToEntity -(dto->entity 변환)
repository:save -(저장)
dto : RequestSingupDTO - (회원가입할때 요청하는 정보들)
> feat:회원가입기능구현

- user-service/src/main/java/com/wesell/userservice/controller/UserController.java
- user-service/src/main/java/com/wesell/userservice/domain/repository/UserRepository.java
- user-service/src/main/java/com/wesell/userservice/dto/SignupRequestDto.java
- user-service/src/main/java/com/wesell/userservice/dto/responseDto.java
- user-service/src/main/java/com/wesell/userservice/service/UserService.java
- user-service/src/main/resources/application.yml
- user-service/src/test/java/com/wesell/userservice/domain/repository/UserRepositoryTest.java
1.회원수정 구현했습니다.
2.추가된 메소드(기능)
UserController - updateUser(수정)
UserService - updateUser(수정)
UserRepository - update(수정)
3.review feedback
RequestSignupDTO -> SignupRequestDto로 바꿨습니다.
> feat: 회원수정구현 

- deal-service/src/main/java/com/wesell/dealservice/DealServiceApplication.java
- deal-service/src/main/java/com/wesell/dealservice/controller/CategoryController.java
- deal-service/src/main/java/com/wesell/dealservice/controller/DealController.java
- deal-service/src/main/java/com/wesell/dealservice/domain/dto/request/CreateDealPostRequestDto.java
- deal-service/src/main/java/com/wesell/dealservice/domain/dto/response/EditPostResponseDto.java
- deal-service/src/main/java/com/wesell/dealservice/domain/dto/response/PostInfoResponseDto.java
- deal-service/src/main/java/com/wesell/dealservice/domain/entity/DealPost.java
- deal-service/src/main/java/com/wesell/dealservice/domain/repository/DealRepository.java
- deal-service/src/main/java/com/wesell/dealservice/feignClient/UserFeignClient.java
- deal-service/src/main/java/com/wesell/dealservice/service/DealService.java
- deal-service/src/main/java/com/wesell/dealservice/service/DealServiceImpl.java
어떤 서비스인지 서비스클래스에 주석 달았습니다.
게시글 상세 보기페이지에 뿌릴 유저측 닉네임 받아오도록 fiegnClient로 요청 보냈습니다!
유저 서비스에서 딜 서비스로 닉네임만 보내줄 메소드 구현해야 하는데 제가 할까요? 충돌날까봐 먼저 물어보고 진행하려구요!
> feat: 게시글 수정, 삭제, 게시글 상세 보기 

- deal-service/src/main/java/com/wesell/dealservice/error/ErrorCode.java
- deal-service/src/main/java/com/wesell/dealservice/error/exception/CustomException.java
- user-service/src/main/java/com/wesell/userservice/controller/UserController.java
- user-service/src/main/java/com/wesell/userservice/domain/repository/UserRepository.java
- user-service/src/main/java/com/wesell/userservice/service/UserService.java
상세 글 보기에 필요한 유저닉네임을
deal service에서 feign으로 요청하면 user-service에서 보내주는 기능입니다.
> feat: deal service에 닉네임 전송 기능

- deal-service/src/main/java/com/wesell/dealservice/controller/CategoryController.java
- deal-service/src/main/java/com/wesell/dealservice/controller/DealController.java
- deal-service/src/main/java/com/wesell/dealservice/domain/entity/DealPost.java
- deal-service/src/main/java/com/wesell/dealservice/dto/request/CreateCategoryRequestDto.java
- deal-service/src/main/java/com/wesell/dealservice/dto/request/CreateDealPostRequestDto.java
- deal-service/src/main/java/com/wesell/dealservice/dto/request/EditPostRequestDto.java
- deal-service/src/main/java/com/wesell/dealservice/dto/response/EditPostResponseDto.java
- deal-service/src/main/java/com/wesell/dealservice/dto/response/ErrorResponseDto.java
- deal-service/src/main/java/com/wesell/dealservice/dto/response/PostInfoResponseDto.java
- deal-service/src/main/java/com/wesell/dealservice/error/ControllerAdvisor.java
- deal-service/src/main/java/com/wesell/dealservice/error/ErrorCode.java
- deal-service/src/main/java/com/wesell/dealservice/error/exception/CustomException.java
- deal-service/src/main/java/com/wesell/dealservice/service/CategoryService.java
- deal-service/src/main/java/com/wesell/dealservice/service/DealService.java
- deal-service/src/main/java/com/wesell/dealservice/service/DealServiceImpl.java
custom exception 구현했습니다.
기능 구현하며 상황에 따라 필요한 에러 문구는 이넘에 추가하여 사용할 예정입니다.
exception이 필요하다고 생각했는데 막상 구현해서 적용하려고 보니 어느 부분에서 사용해야 할 지 모르겠습니다 ㅎㅎ..
deal service에 예외 던지는 경우가 언제 있을까요..?
++ dto 패키지 위치 수정 있었는데 커밋에 못 나눴습니다! 다음부턴 주의하겠슴다
> feat: 커스텀 예외 처리 기능

- user-service/src/main/java/com/wesell/userservice/controller/UserController.java
- user-service/src/main/java/com/wesell/userservice/domain/repository/UserRepository.java
- user-service/src/main/java/com/wesell/userservice/dto/response/MypageResponseDto.java
- user-service/src/main/java/com/wesell/userservice/dto/response/ResponseDto.java
- user-service/src/main/java/com/wesell/userservice/service/UserService.java
1.마이페이지1에 사용자정보보기 구현했습니다.
조회를 하면  name,nickname,phone 나오게끔 구현했습니다.
추후 feign client를 이용하여 email도 볼 수 있도록 구현하겠습니다.
> feat:마이페이지 사용자정보보기구현

- authentication-server/src/main/java/com/wesell/authenticationserver/controller/AuthController.java
- authentication-server/src/main/java/com/wesell/authenticationserver/domain/entity/TokenInfo.java
- authentication-server/src/main/java/com/wesell/authenticationserver/domain/repository/AuthUserRepository.java
- authentication-server/src/main/java/com/wesell/authenticationserver/dto/GeneratedTokenDto.java
- authentication-server/src/main/java/com/wesell/authenticationserver/filter/JwtAuthenticationFilter.java
- authentication-server/src/main/java/com/wesell/authenticationserver/global/util/CustomConverter.java
- authentication-server/src/main/java/com/wesell/authenticationserver/global/util/CustomCookie.java
- authentication-server/src/main/java/com/wesell/authenticationserver/response/CustomException.java
- authentication-server/src/main/java/com/wesell/authenticationserver/response/ErrorCode.java
- authentication-server/src/main/java/com/wesell/authenticationserver/response/ErrorControllerAdvisor.java
- authentication-server/src/main/java/com/wesell/authenticationserver/response/ErrorResponseDto.java
- authentication-server/src/main/java/com/wesell/authenticationserver/service/AuthUserService.java
- authentication-server/src/main/java/com/wesell/authenticationserver/service/TokenInfoService.java
- authentication-server/src/main/java/com/wesell/authenticationserver/service/UserDetailsImpl.java
- authentication-server/src/main/java/com/wesell/authenticationserver/service/UserDetailsServiceImpl.java
- authentication-server/src/main/java/com/wesell/authenticationserver/service/token/TokenProvider.java
🎇 feat: CustomException 구현, 일괄 예외처리 구현
- RuntimeException을 상속한 CustomException 구현.
- 발생할 메시지 및, 응답 상태 코드, 에러 코드 커스텀할 수 있도록 구현.
🎇 feat: 토큰 권한 확인 및 처리를 위한 전처리 기능 구현.
- token 생성 및 로그인 기능 수정.
- 아이디 저장 기능 쿠키 사용하여 구현.
- 토큰 검증을 위한 기능 구현(validateToken)
🎇 feat: 커스텀 필터 구현 - 권한 부여, 기한 만료된 토큰 처리, 그 외 비정상 토큰 처리
- 현재 필터 내 기능들을 구현하였으나, 로그아웃할 경우의 상황을 추가로 고려해야 하여 다음 PR에 수정한 로직 추가예정임.
> [Auth] - 권한 확인 커스텀 필터 구현

- user-service/src/main/java/com/wesell/userservice/controller/UserController.java
- user-service/src/main/java/com/wesell/userservice/domain/entity/User.java
- user-service/src/main/java/com/wesell/userservice/service/UserService.java
1.review feedback
2.회원정보수정코드추가
회원이 정보를 수정했을때의 변경시간을 db에 저장하도록 코드를 추가했다.
> fix:마이페이지 사용자정보보기구현 수정

- user-service/src/main/java/com/wesell/userservice/controller/FindIDController.java
- user-service/src/main/java/com/wesell/userservice/domain/repository/UserRepository.java
- user-service/src/main/java/com/wesell/userservice/dto/response/FindIDResponseDto.java
- user-service/src/main/java/com/wesell/userservice/global/util/SmsUtil.java
- user-service/src/main/java/com/wesell/userservice/service/AdminFeignService.java
- user-service/src/main/java/com/wesell/userservice/service/FindIDService.java
- user-service/src/main/java/com/wesell/userservice/service/UserService.java
- user-service/src/main/resources/application.yml
- user-service/src/test/java/com/wesell/userservice/domain/repository/UserRepositoryTest.java
* 아이디 찾기 기능 구현 완료
- 아이디 찾기 기능 테스트 완료
- SmsUtil 클래스에 인증번호 일치 여부를 판단하는 메서드 생성완료, 메시지 발송 시 인증번호를 임시 저장 후 일치 판단.
- 인증 번호 발송 후, 사용자가 인증번호를 입력하면 미리 저장되었던 인증번호와 일치 여부 판단 후 해당 전화번호로 uuid값을 찾는 메서드로 uuid값을 리턴함
- 만약 인증번호를 db나 캐시에 저장해놓지 않고 전역변수에만 저장해두면 인증번호 요청이 동시다발적으로 들어올 때, 인증번호가 맞아도 틀리게 되는 현상 발생 가능. 이 문제는 회의 때 팀원들과 검토해봐야 할듯!!
- 이외에도 수정사항이나 추가할 사항 있으면 자유롭게 댓글 바랍니다~
> feat: 아이디 찾기 기능 구현

- user-service/src/main/java/com/wesell/userservice/controller/UserController.java
- user-service/src/main/java/com/wesell/userservice/domain/repository/UserRepository.java
- user-service/src/main/java/com/wesell/userservice/service/UserService.java
Deal server가 uuid를 통해 닉네임받는 기능을 구현했습니다.
> Feat: [Deal/User] - 닉네임 받기

- admin-service/src/main/java/com/wesell/adminservice/controller/AdminController.java
- admin-service/src/main/java/com/wesell/adminservice/domain/enum_/Role.java
- admin-service/src/main/java/com/wesell/adminservice/dto/response/PostListResponseDto.java
- admin-service/src/main/resources/application.yml
```java
public enum Role {
USER
ADMIN
}
``` 
```java
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class PostListResponseDto {
private String title;
private LocalDate createdAt;
private SaleStatus status;
}
```
> fix: feign 기능 수정

- user-service/src/main/java/com/wesell/userservice/domain/entity/User.java
- user-service/src/main/java/com/wesell/userservice/dto/response/ResponseDto.java
- user-service/src/main/resources/application.yml
> feat: 유저 엔티티 수정

- deal-service/src/main/java/com/wesell/dealservice/controller/usercontroller/NicknameController.java
- deal-service/src/main/java/com/wesell/dealservice/dto/userdto/NicknameDto.java
- deal-service/src/main/java/com/wesell/dealservice/feignClient/UserFeignClient.java
- user-service/src/main/java/com/wesell/userservice/controller/UserController.java
Dealservice에서 feign 통해 닉네임 받는 코드 구현했습니다.
> feat: Dealservice feign 닉네임 받기 구현

- deal-service/.gitignore
- deal-service/build.gradle
- deal-service/src/main/java/com/wesell/dealservice/controller/AdminDealController.java
- deal-service/src/main/java/com/wesell/dealservice/controller/DealController.java
- deal-service/src/main/java/com/wesell/dealservice/domain/dto/queryDSL/DealPostInfoDto.java
- deal-service/src/main/java/com/wesell/dealservice/domain/repository/read/DealPostReadRepository.java
- deal-service/src/main/java/com/wesell/dealservice/service/AdminDealService.java
- deal-service/src/main/java/com/wesell/dealservice/service/DealService.java
- deal-service/src/main/java/com/wesell/dealservice/service/DealServiceImpl.java
- deal-service/src/main/resources/application.yml
- deal-service/src/test/java/com/wesell/dealservice/DealServiceApplicationTests.java
쿼리사용하여 조회 기능을 최적화하였습니다.
cqrs 패턴을 도입하려고 했는데 레디스랑 캐시 기능 구현해야 돼서 그건 다음주 중으로 완료될 것 같습니다! 본의아니게 리팩토링하는 시간이 되었네요 ㅎㅎ
> ref: 쿼리 최적화

- config-server/.gitignore
- deal-service/src/main/java/com/wesell/dealservice/controller/CategoryController.java
- deal-service/src/main/java/com/wesell/dealservice/controller/DealController.java
- deal-service/src/main/java/com/wesell/dealservice/domain/dto/request/UploadDealPostRequestDto.java
- deal-service/src/main/java/com/wesell/dealservice/domain/dto/response/MyPostListResponseDto.java
- deal-service/src/main/java/com/wesell/dealservice/domain/dto/response/PostInfoResponseDto.java
- deal-service/src/main/java/com/wesell/dealservice/domain/entity/DealPost.java
- deal-service/src/main/java/com/wesell/dealservice/service/DealServiceImpl.java
- front-server/src/App.tsx
- front-server/src/constant/index.tsx
- front-server/src/pages/board/write/Write.tsx
LocalDateTime 타입으로 저장하고 responseDto에는 포맷한 string 값으로 전달합니다.
> fix: localdatetime 수정

- authentication-server/src/main/java/com/wesell/authenticationserver/AuthenticationServerApplication.java
- authentication-server/src/main/java/com/wesell/authenticationserver/controller/AuthController.java
- authentication-server/src/main/java/com/wesell/authenticationserver/controller/AuthFeignController.java
- authentication-server/src/main/java/com/wesell/authenticationserver/domain/entity/AuthUser.java
- authentication-server/src/main/java/com/wesell/authenticationserver/global/util/SmsUtil.java
- authentication-server/src/main/resources/application.yml
- deal-service/build.gradle
- deal-service/src/main/java/com/wesell/dealservice/controller/DealController.java
- deal-service/src/main/java/com/wesell/dealservice/domain/dto/response/MyPostListResponseDto.java
- deal-service/src/main/java/com/wesell/dealservice/domain/dto/response/PageResponseDto.java
- deal-service/src/main/java/com/wesell/dealservice/domain/entity/DealPost.java
- deal-service/src/main/java/com/wesell/dealservice/redis/RedisCacheConfig.java
- deal-service/src/main/java/com/wesell/dealservice/redis/RedisConfig.java
- deal-service/src/main/java/com/wesell/dealservice/service/DealService.java
- deal-service/src/main/java/com/wesell/dealservice/service/DealServiceImpl.java
- deal-service/src/main/java/com/wesell/dealservice/service/FileUploadService.java
- deal-service/src/main/java/com/wesell/dealservice/util/Consumer.java
- deal-service/src/main/resources/application.yml
- front-server/.idea/workspace.xml
- front-server/package-lock.json
* Redis 환경설정 및 구현, 메시지큐 수정 완료
- Redis 캐시 서버 도입하였고 메인페이지, 마이페이지 post 조회하는 로직에 구현하였습니다.
- Redis 서버 테스트 완료
- 메시지큐에서 컨트롤러로 return 값 반환하는 로직 추가로 구현하였습니다.
- 이외에도 수정사항이나 추가할 사항 있으면 댓글 바랍니다~
> Redis 환경설정 및 구현

- apigateway-server/src/main/resources/application.yml
- authentication-server/src/main/java/com/wesell/authenticationserver/global/util/SmsUtil.java
- deal-service/src/main/java/com/wesell/dealservice/domain/repository/read/DealPostReadRepository.java
- deal-service/src/main/java/com/wesell/dealservice/feignClient/UserFeignClient.java
- deal-service/src/main/java/com/wesell/dealservice/service/DealServiceImpl.java
- front-server/package-lock.json
- front-server/package.json
- front-server/src/App.tsx
- front-server/src/pages/board/detail/index.css
- front-server/src/pages/board/detail/index.tsx
> fix: 통합 테스트 1차 완료

- deal-service/src/main/java/com/wesell/dealservice/controller/DealController.java
- front-server/src/App.tsx
- front-server/src/components/ImageUploader/ImageUploader.css
- front-server/src/components/ImageUploader/ImageUploader.js
- front-server/src/components/Pagenation/index.tsx
- front-server/src/components/TextArea/style.css
- front-server/src/pages/Main/index.tsx
- front-server/src/pages/Main/style.css
- front-server/src/pages/board/detail/index.tsx
- front-server/src/pages/board/edit/index.css
- front-server/src/pages/board/edit/index.tsx
- front-server/src/pages/board/write/Write.css
- front-server/src/pages/board/write/Write.tsx
- front-server/src/pages/search/category.tsx
- front-server/src/pages/search/title.tsx
main, search 페이지에 페이징 달았습니다.
검색 결과 없는 경우 '검색결과 없음' 문구 내보냅니다.
> 배포 준비를 위한 머지
